# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fRh2T5t5EK1FBdD4llNnJdgAKKWR-wm
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("Nat_Gas.csv")

# Convert Dates column into actual date format
df['Dates'] = pd.to_datetime(df['Dates'])

# Check data
print(df.head())

# Plot graph
plt.figure(figsize=(12,6))

plt.plot(df['Dates'], df['Prices'], marker='o')

plt.title("Natural Gas Prices Over Time")

plt.xlabel("Date")
plt.ylabel("Price")

plt.grid(True)

plt.show()

df['Dates'] = pd.to_datetime(df['Dates'], format='%m/%d/%y')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from scipy.interpolate import interp1d

# Load data
df = pd.read_csv("Nat_Gas.csv")

# Convert dates
df['Dates'] = pd.to_datetime(df['Dates'], format='%m/%d/%y')

# Create graph
plt.figure(figsize=(12,6))
plt.plot(df['Dates'], df['Prices'], marker='o')
plt.title("Natural Gas Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.grid(True)
plt.show()

# Create month index
df['Month_Index'] = np.arange(len(df))

# Train model
X = df[['Month_Index']]
y = df['Prices']

model = LinearRegression()
model.fit(X, y)

# Predict next 12 months
future_months = 12

future_index = np.arange(len(df), len(df) + future_months)

future_dates = pd.date_range(
    start=df['Dates'].iloc[-1] + pd.offsets.MonthEnd(1),
    periods=future_months,
    freq='M'
)

future_prices = model.predict(future_index.reshape(-1,1))

# Future dataframe
future_df = pd.DataFrame({
    'Dates': future_dates,
    'Prices': future_prices
})

# Plot forecast
plt.figure(figsize=(12,6))

plt.plot(df['Dates'], df['Prices'],
         marker='o',
         label='Historical')

plt.plot(future_df['Dates'], future_df['Prices'],
         linestyle='--',
         marker='x',
         label='Forecast')

plt.title("Natural Gas Price Forecast")
plt.xlabel("Date")
plt.ylabel("Price")

plt.legend()
plt.grid(True)

plt.show()

# Combine all data
combined_df = pd.concat([
    df[['Dates','Prices']],
    future_df
])

# Convert dates to numbers
combined_df['Numeric_Date'] = combined_df['Dates'].map(pd.Timestamp.toordinal)

# Interpolation
interp_function = interp1d(
    combined_df['Numeric_Date'],
    combined_df['Prices'],
    kind='linear',
    fill_value='extrapolate'
)

# Final function
def estimate_price(input_date):

    input_date = pd.to_datetime(input_date)

    numeric_date = input_date.toordinal()

    estimated_price = interp_function(numeric_date)

    return round(float(estimated_price), 2)

# Example
print(estimate_price("2025-06-15"))