# -*- coding: utf-8 -*-
"""running_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/astg606/py_materials/blob/master/welcome/running_python.ipynb
"""

import pandas as pd

def price_contract(
    buy_price,
    sell_price,
    quantity,
    storage_cost_per_month,
    months
):

    # Purchase cost
    purchase_cost = buy_price * quantity

    # Selling revenue
    revenue = sell_price * quantity

    # Storage cost
    storage_cost = storage_cost_per_month * months

    # Final contract value
    contract_value = revenue - purchase_cost - storage_cost

    return contract_value


# Example test
value = price_contract(
    buy_price = 10,
    sell_price = 14,
    quantity = 1000,
    storage_cost_per_month = 500,
    months = 4
)

print("Contract Value =", value)

